- modular/optionAutorespond.js
> Added cooldown to AFK response

- .gitignore
- asset.css
- beta.js
- modular/hello.js
I also tweak a few things like missing or unnecessary semi-colons cause my JShint was throwing error notifications
> NameSpace the plugin

- beta.js
I know Dubtrack is adding this soon. But why not have it while we wait? They have other things to do so it may take a while.
> Added CSS classes in chat (Final update)

- beta.js
This has been bothering me more than you think.
> Fixed medium element not disappearing when changing background.

- beta.js
- css/options/emoji.css
let me know if this works well for you
> increased twitch emoji size and added autoselect if 1 emoji is in preview

- beta.js
- css/asset.css
it's easier to just use nth-child in the CSS rather than with jquery
> fixing split chat 

- beta.js
- css/options/chat_window.css
- css/options/video_window.css
- js/dubx.js
- js/test.js
- themes/PlugTheme.css
to remove the need to write "!important" for in CSS
> Caching Twitch API

- beta.js
Add ability to display a web api notification when the user is mentioned in chat
> Notifcations when mentioned

- README.md
- beta.js
How else are people supposed to know of new changes?!
> Change version number

- .gitignore
- README.md
- beta.js
- css/asset.css
* Add open/close icons for sections and combined drawSection functions into one
* Update version number
Added myself as a contributor in the Readme as well, I'll remove it if you guys don't agree
> Ui toggles

- css/asset.css
Small css fixes where colors for DubX devs didn't properly display in some rooms' userlist
> Minor css fixes

- README.md
- beta.js
Fix for message sending when trying to select anything in the autocomplete list by hitting enter, fix spelling error in function name and update version number
> Autocomplete Enter Press Fix

- beta.js
- css/asset.css
Fix double scrollbar and slow scroll speed
> Scrollbar fix

- beta.js
This helps the new vote limit set in place
> Check for user's existing vote on active song before trying to upvote

- beta.js
Save the display state of each section in localStorage, fix version number to properly open and close sections, add title to version number link to let users know about action
> Section state localstorage

- README.md
- beta.js
- Added ability to set custom text phrases that trigger a mention sound
- Notifications now check for custom mention triggers as well
> Custom mention triggers

- beta.js
> Fix input function to put current content in the input field

- beta.js
Fix mention sound playing when one of the user's custom triggers is sent in chat by themselves
> Custom mention trigger fix

- beta.js
Fixed notification custom mention trigger lookup being case sensitive
> Case sensitive custom trigger notification fix

- beta.js
Don't send afk chat respond if the mention was by the same user, don't send notification if mention or custom trigger was by the same user
> AFK Message and Notification Fixes

- beta.js
Fix for people not deleting the placeholder text of a bug report
> Bug Report Placeholder Fix

- beta.js
Fix bug where user would still get web notifications on custom triggers even if custom triggers were still off
> Notifications still sending if custom triggers turned off fix

- beta.js
Overwrote options variable in a function... whoops
> Fix let_custom_mentions crash

- beta.js
30 seconds was way too low and spammed chat when person returns for a few minutes
> bump afk response time to 3 minutes

- beta.js
and I bet this won't be the last autocomplete fixes.
> some more autocomplete fixes

- beta.js
This removes the actual issue preventing dubx from loading.
> Fix loading issue

- css/asset.css
this should do the trick.  I left "Admin" in there because I looked through the updates from DT and I didn't see that role mentioned.
> fix to remove duplicate room roles after recent front-end update by dubtrack

- beta.js
- css/asset.css
Fixes user roles and other bugs where colors weren't being updated
> CSS updates for Dubtrack UI changes

- beta.js
- css/README.md
- css/asset.css
- css/options/autocomplete.css
worked when I tested it out 
I also made sure my master was up to date
there are SOOO many new emojis now!
> this should fix emoji autocomplete 
